// Generated by CoffeeScript 1.6.2
(function($) {
  "use strict";  return $(document).ready(function() {
    var resize;

    resize = function() {
      var $element, height;

      height = $(window).height();
      $element = $('img.attachment-image');
      return $element.each(function() {
        return $element.css({
          'max-height': (height - 61 - 60 - 20) + 'px'
        });
      });
    };
    $(window).resize(resize);
    return setTimeout(resize, 0);
  });
})(window.jQuery);
