// Generated by CoffeeScript 1.6.2
(function($) {
  return $('a[href^=#]').click(function() {
    var href, position, speed, target;

    speed = 500;
    href = $(this).attr('href');
    if (href === '#' || href === '') {
      target = $('html');
    } else {
      target = $(href);
    }
    position = target.offset().top;
    $('html,body').animate({
      scrollTop: position
    }, speed, 'swing');
    return false;
  });
})(window.jQuery);
