// Generated by CoffeeScript 1.6.3
$(document).ready(function() {
  $('#btn-navbar').click(function() {
    return $('.navbar-responsive-collapse').collapse('toggle');
  });
  $('.navbar-responsive-collapse').on('show.bs.collapse', function() {
    var $icon;
    $icon = $('.icon-btn-navbar');
    if (!$icon.hasClass('menu-open')) {
      return $icon.addClass('menu-open');
    }
  });
  return $('.navbar-responsive-collapse').on('hide.bs.collapse', function() {
    var $icon;
    $icon = $('.icon-btn-navbar');
    if ($icon.hasClass('menu-open')) {
      return $icon.removeClass('menu-open');
    }
  });
});
