// Generated by CoffeeScript 1.6.3
(function($) {
  "use strict";
  return $(document).ready(function() {
    return $('.widget-area').masonry({
      itemSelector: '.widget'
    });
  });
})(window.jQuery);
